# Generated by Django 5.2.2 on 2025-06-07 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("rank", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cash_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("games_played", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("win_streak", models.IntegerField(default=0)),
                ("Achievements", models.IntegerField(default=0)),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_pictures/"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Novice", "Novice"),
                            ("Pattern Seeker", "Pattern Seeker"),
                            ("Neural Thinker", "Neural Thinker"),
                            ("Prompt Decoder", "Prompt Decoder"),
                            ("Human GPT", "Human GPT"),
                            ("Prompt Architect", "Prompt Architect"),
                            ("GOD OF AI", "GOD OF AI"),
                        ],
                        default="Novice",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userdata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
