# Generated by Django 5.2.2 on 2025-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersdata",
            name="phone",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
