# Generated by Django 5.2.2 on 2025-06-12 02:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_usersdata_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=100)),
                ("game_description", models.TextField()),
                ("game_image", models.ImageField(upload_to="game_images/")),
                (
                    "game_category",
                    models.CharField(
                        choices=[
                            ("FPS", "FPS"),
                            ("Strategy", "Strategy"),
                            ("RPG", "RPG"),
                            ("Adventure", "Adventure"),
                            ("Racing", "Racing"),
                            ("Sports", "Sports"),
                        ],
                        default="FPS",
                        max_length=50,
                    ),
                ),
                ("game_players", models.IntegerField(default=1)),
                (
                    "game_duration",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
                (
                    "game_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="usersdata",
            name="email",
        ),
        migrations.CreateModel(
            name="LudoGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moves", models.JSONField(blank=True, default=list)),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ludo_games",
                        to="core.gamedata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ludo_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ludo_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="prompt_images/"
                    ),
                ),
                ("user_prompt", models.TextField(blank=True, null=True)),
                (
                    "similarity_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_games",
                        to="core.gamedata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
