# Generated by Django 5.2.2 on 2025-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_gamedata_remove_usersdata_email_ludogame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersdata",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
